export const PERMISSIONS = {
  // Admin Panel
  VIEW_ADMIN_PANEL: 'VIEW_ADMIN_PANEL',

  // Users
  VIEW_USERS: 'VIEW_USERS',
  MANAGE_USERS: 'MANAGE_USERS',

  // Credits
  VIEW_CREDITS: 'VIEW_CREDITS',
  MANAGE_CREDITS: 'MANAGE_CREDITS',

  // Cautions
  VIEW_CAUTIONS: 'VIEW_CAUTIONS',
  MANAGE_CAUTIONS: 'MANAGE_CAUTIONS',

  // Roles
  VIEW_ROLES: 'VIEW_ROLES',
  MANAGE_ROLES: 'MANAGE_ROLES',

  // Invitations
  VIEW_INVITATIONS: 'VIEW_INVITATIONS',
  MANAGE_INVITATIONS: 'MANAGE_INVITATIONS',

  // Audit
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  EXPORT_AUDIT_LOGS: 'EXPORT_AUDIT_LOGS',

  // Files
  VIEW_FILES: 'VIEW_FILES',
  MANAGE_FILES: 'MANAGE_FILES',

  // Sections
  VIEW_SECTIONS: 'VIEW_SECTIONS',
  MANAGE_SECTIONS: 'MANAGE_SECTIONS',

  // Products
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',

  // Reservations
  VIEW_RESERVATIONS: 'VIEW_RESERVATIONS',
  MANAGE_RESERVATIONS: 'MANAGE_RESERVATIONS',

  // Statistics
  VIEW_STATISTICS: 'VIEW_STATISTICS',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
