export const PERMISSIONS = {
  // Users
  VIEW_USERS: "VIEW_USERS",
  MANAGE_USERS: "MANAGE_USERS",

  // Credits
  VIEW_CREDITS: "VIEW_CREDITS",
  MANAGE_CREDITS: "MANAGE_CREDITS",

  // Cautions
  MANAGE_CAUTIONS: "MANAGE_CAUTIONS",

  // Roles
  VIEW_ROLES: "VIEW_ROLES",
  MANAGE_ROLES: "MANAGE_ROLES",

  // Sections
  MANAGE_SECTIONS: "MANAGE_SECTIONS",

  // Products
  VIEW_PRODUCTS: "VIEW_PRODUCTS",
  MANAGE_PRODUCTS: "MANAGE_PRODUCTS",

  // Reservations
  VIEW_RESERVATIONS: "VIEW_RESERVATIONS",
  MANAGE_RESERVATIONS: "MANAGE_RESERVATIONS",

  // Statistics
  VIEW_STATISTICS: "VIEW_STATISTICS",

  // Settings
  VIEW_SETTINGS: "VIEW_SETTINGS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",

  // Maintenance
  BYPASS_MAINTENANCE: "BYPASS_MAINTENANCE",
  BACKUP_DATABASE: "BACKUP_DATABASE",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
