export const PERMISSIONS = {
  // Admin Panel
  VIEW_ADMIN_PANEL: 'VIEW_ADMIN_PANEL',

  // Users
  VIEW_USERS: 'VIEW_USERS',
  MANAGE_USERS: 'MANAGE_USERS',
  CREATE_USERS: 'CREATE_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  DELETE_USERS: 'DELETE_USERS',
  SUSPEND_USERS: 'SUSPEND_USERS',

  // Credits
  VIEW_CREDITS: 'VIEW_CREDITS',
  MANAGE_CREDITS: 'MANAGE_CREDITS',
  ADJUST_CREDITS: 'ADJUST_CREDITS',
  VIEW_CREDIT_HISTORY: 'VIEW_CREDIT_HISTORY',

  // Caution
  VIEW_CAUTION: 'VIEW_CAUTION',
  MANAGE_CAUTION: 'MANAGE_CAUTION',
  VALIDATE_CAUTION: 'VALIDATE_CAUTION',
  EXEMPT_CAUTION: 'EXEMPT_CAUTION',

  // Roles
  VIEW_ROLES: 'VIEW_ROLES',
  MANAGE_ROLES: 'MANAGE_ROLES',
  CREATE_ROLES: 'CREATE_ROLES',
  UPDATE_ROLES: 'UPDATE_ROLES',
  DELETE_ROLES: 'DELETE_ROLES',
  ASSIGN_ROLES: 'ASSIGN_ROLES',

  // Invitations
  VIEW_INVITATIONS: 'VIEW_INVITATIONS',
  MANAGE_INVITATIONS: 'MANAGE_INVITATIONS',
  CREATE_INVITATIONS: 'CREATE_INVITATIONS',
  CANCEL_INVITATIONS: 'CANCEL_INVITATIONS',

  // Audit
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  EXPORT_AUDIT_LOGS: 'EXPORT_AUDIT_LOGS',

  // Files
  VIEW_FILES: 'VIEW_FILES',
  MANAGE_FILES: 'MANAGE_FILES',
  DELETE_FILES: 'DELETE_FILES',
} as const

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS]

export const PERMISSION_HIERARCHY: Record<string, string[]> = {
  // Admin Panel gives access to everything
  VIEW_ADMIN_PANEL: [
    'VIEW_USERS',
    'VIEW_CREDITS',
    'VIEW_CAUTION',
    'VIEW_ROLES',
    'VIEW_INVITATIONS',
    'VIEW_AUDIT_LOGS',
    'VIEW_FILES',
  ],

  // Users
  MANAGE_USERS: ['VIEW_USERS', 'CREATE_USERS', 'UPDATE_USERS', 'DELETE_USERS', 'SUSPEND_USERS'],

  // Credits
  MANAGE_CREDITS: ['VIEW_CREDITS', 'ADJUST_CREDITS', 'VIEW_CREDIT_HISTORY'],

  // Caution
  MANAGE_CAUTION: ['VIEW_CAUTION', 'VALIDATE_CAUTION', 'EXEMPT_CAUTION'],

  // Roles
  MANAGE_ROLES: ['VIEW_ROLES', 'CREATE_ROLES', 'UPDATE_ROLES', 'DELETE_ROLES', 'ASSIGN_ROLES'],

  // Invitations
  MANAGE_INVITATIONS: ['VIEW_INVITATIONS', 'CREATE_INVITATIONS', 'CANCEL_INVITATIONS'],

  // Audit
  EXPORT_AUDIT_LOGS: ['VIEW_AUDIT_LOGS'],

  // Files
  MANAGE_FILES: ['VIEW_FILES', 'DELETE_FILES'],
}

export const PERMISSION_CATEGORIES = {
  ADMIN: 'ADMIN',
  USERS: 'USERS',
  CREDITS: 'CREDITS',
  CAUTION: 'CAUTION',
  ROLES: 'ROLES',
  INVITATIONS: 'INVITATIONS',
  AUDIT: 'AUDIT',
  FILES: 'FILES',
} as const

export type PermissionCategory = typeof PERMISSION_CATEGORIES[keyof typeof PERMISSION_CATEGORIES]

export const PERMISSIONS_BY_CATEGORY: Record<PermissionCategory, PermissionKey[]> = {
  ADMIN: ['VIEW_ADMIN_PANEL'],
  USERS: [
    'VIEW_USERS',
    'MANAGE_USERS',
    'CREATE_USERS',
    'UPDATE_USERS',
    'DELETE_USERS',
    'SUSPEND_USERS',
  ],
  CREDITS: [
    'VIEW_CREDITS',
    'MANAGE_CREDITS',
    'ADJUST_CREDITS',
    'VIEW_CREDIT_HISTORY',
  ],
  CAUTION: [
    'VIEW_CAUTION',
    'MANAGE_CAUTION',
    'VALIDATE_CAUTION',
    'EXEMPT_CAUTION',
  ],
  ROLES: [
    'VIEW_ROLES',
    'MANAGE_ROLES',
    'CREATE_ROLES',
    'UPDATE_ROLES',
    'DELETE_ROLES',
    'ASSIGN_ROLES',
  ],
  INVITATIONS: [
    'VIEW_INVITATIONS',
    'MANAGE_INVITATIONS',
    'CREATE_INVITATIONS',
    'CANCEL_INVITATIONS',
  ],
  AUDIT: [
    'VIEW_AUDIT_LOGS',
    'EXPORT_AUDIT_LOGS',
  ],
  FILES: [
    'VIEW_FILES',
    'MANAGE_FILES',
    'DELETE_FILES',
  ],
}
